/* eslint-disable camelcase */
/*
* Arcade
 */
module.exports = ({
  coins = 0,
  // Blocking Dead
  wins_dayone = 0,
  kills_dayone = 0,
  headshots_dayone = 0,
  melee_weapon = null,
  // Dragonwars
  wins_dragonwars2 = 0,
  kills_dragonwars2 = 0,
  // Ender Spleef
  wins_ender = 0,
  blocks_destroyed_ender = 0,
  powerup_activations_ender = 0,
  bigshot_powerup_activations_ender = 0,
  tripleshot_powerup_activations_ender = 0,
  // Hypixel Says
  wins_simon_says = 0,
  rounds_simon_says = 0,
  round_wins_simon_says = 0,
  top_score_simon_says = 0,
  // Santa Says
  wins_santa_says = 0,
  rounds_santa_says = 0,
  round_wins_santa_says = 0,
  top_score_santa_says = 0,
  // Mini Walls
  wins_mini_walls = 0,
  kills_mini_walls = 0,
  deaths_mini_walls = 0,
  final_kills_mini_walls = 0,
  arrows_shot_mini_walls = 0,
  arrows_hit_mini_walls = 0,
  wither_damage_mini_walls = 0,
  wither_kills_mini_walls = 0,
  miniwalls_activeKit = null,
  // Party Games
  wins_party = 0,
  wins_party_2 = 0,
  wins_party_3 = 0,
  round_wins_party = 0,
  total_stars_party = 0,
  animal_slaughter_round_wins_party = 0,
  animal_slaughter_kills_party = 0,
  animal_slaughter_best_score_party = 0,
  anvil_spleef_round_wins_party = 0,
  anvil_spleef_best_time_party = 0,
  bombardment_round_wins_party = 0,
  bombardment_best_time_party = 0,
  chicken_rings_round_wins_party = 0,
  chicken_rings_best_time_party = 0,
  dive_round_wins_party = 0,
  dive_total_score_party = 0,
  dive_best_score_party = 0,
  high_ground_round_wins_party = 0,
  high_ground_total_score_party = 0,
  high_ground_best_score_party = 0,
  hoe_hoe_hoe_round_wins_party = 0,
  hoe_hoe_hoe_total_score_party = 0,
  hoe_hoe_hoe_best_score_party = 0,
  jigsaw_rush_round_wins_party = 0,
  jigsaw_rush_best_time_party = 0,
  jungle_jump_round_wins_party = 0,
  jungle_jump_best_time_party = 0,
  lab_escape_round_wins_party = 0,
  lab_escape_best_time_party = 0,
  lawn_moower_round_wins_party = 0,
  lawn_moower_mowed_total_score_party = 0,
  lawn_moower_mowed_best_score_party = 0,
  minecart_racing_round_wins_party = 0,
  minecart_racing_best_time_party = 0,
  rpg_16_round_wins_party = 0,
  rpg_16_kills_party = 0,
  rpg_16_kills_best_score_party = 0,
  spider_maze_round_wins_party = 0,
  spider_maze_best_time_party = 0,
  the_floor_is_lava_round_wins_party = 0,
  the_floor_is_lava_best_time_party = 0,
  avalanche_round_wins_party = 0,
  volcano_round_wins_party = 0,
  pig_fishing_round_wins_party = 0,
  pig_jousting_round_wins_party = 0,
  trampolinio_round_wins_party = 0,
  workshop_round_wins_party = 0,
  shooting_range_round_wins_party = 0,
  frozen_floor_round_wins_party = 0,
  cannon_painting_round_wins_party = 0,
  fire_leapers_round_wins_party = 0,
  super_sheep_round_wins_party = 0,
  // Pixel Painters
  wins_draw_their_thing = 0,
  // Throw Out
  wins_throw_out = 0,
  kills_throw_out = 0,
  deaths_throw_out = 0,
  // Bounty Hunters
  wins_oneinthequiver = 0,
  kills_oneinthequiver = 0,
  deaths_oneinthequiver = 0,
  bounty_kills_oneinthequiver = 0,
  bow_kills_oneinthequiver = 0,
  sword_kills_oneinthequiver = 0,
  // Galaxy Wars
  sw_game_wins = 0,
  sw_kills = 0,
  sw_deaths = 0,
  sw_rebel_kills = 0,
  sw_empire_kills = 0,
  sw_shots_fired = 0,
  // Farm Hunt
  wins_farm_hunt = 0,
  animal_wins_farm_hunt = 0,
  hunter_wins_farm_hunt = 0,
  kills_farm_hunt = 0,
  animal_kills_farm_hunt = 0,
  hunter_kills_farm_hunt = 0,
  bow_kills_farm_hunt = 0,
  animal_bow_kills_farm_hunt = 0,
  hunter_bow_kills_farm_hunt = 0,
  taunts_used_farm_hunt = 0,
  safe_taunts_used_farm_hunt = 0,
  risky_taunts_used_farm_hunt = 0,
  dangerous_taunts_used_farm_hunt = 0,
  firework_taunts_used_farm_hunt = 0,
  poop_collected_farm_hunt = 0,
  poop_collected = 0,
  // Football (not soccer)
  wins_soccer = 0,
  goals_soccer = 0,
  powerkicks_soccer = 0,
  kicks_soccer = 0,
  // Creeper Attack
  max_wave = 0,
  // Hole in the Wall
  wins_hole_in_the_wall = 0,
  rounds_hole_in_the_wall = 0,
  hitw_record_q = 0,
  hitw_record_f = 0,
  // Hide and Seek
  prop_hunt_hider_wins_hide_and_seek = 0,
  prop_hunt_seeker_wins_hide_and_seek = 0,
  party_pooper_seeker_wins_hide_and_seek = 0,
  party_pooper_hider_wins_hide_and_seek = 0,
  seeker_wins_hide_and_seek = 0,
  hider_wins_hide_and_seek = 0,
  // Zombies
  wins_zombies = 0,
  wins_zombies_alienarcadium = 0,
  wins_zombies_badblood = 0,
  wins_zombies_deadend = 0,
  deaths_zombies = 0,
  total_rounds_survived_zombies = 0,
  bullets_hit_zombies = 0,
  headshots_zombies = 0,
  players_revived_zombies = 0,
  windows_repaired_zombies = 0,
  doors_opened_zombies = 0,
  zombie_kills_zombies = 0,
  best_round_zombies = 0,
}) => {
  const modes = {
    blocking_dead: {
      wins: wins_dayone,
      zombie_kills: kills_dayone,
      headshots: headshots_dayone,
      weapon: melee_weapon,
    },
    dragonwars: {
      wins: wins_dragonwars2,
      kills: kills_dragonwars2,
    },
    ender_spleef: {
      wins: wins_ender,
      blocks_destroyed: blocks_destroyed_ender,
      powerup_activations: powerup_activations_ender,
      bigshot_activations: bigshot_powerup_activations_ender,
      tripleshot_activations: tripleshot_powerup_activations_ender,
    },
    hypixel_says: {
      wins: wins_simon_says,
      rounds: rounds_simon_says,
      round_wins: round_wins_simon_says,
      top_score: top_score_simon_says,
    },
    santa_says: {
      wins: wins_santa_says,
      rounds: rounds_santa_says,
      round_wins: round_wins_santa_says,
      top_score: top_score_santa_says,
    },
    miniwalls: {
      wins: wins_mini_walls,
      kills: kills_mini_walls,
      deaths: deaths_mini_walls,
      final_kills: final_kills_mini_walls,
      arrows_shot: arrows_shot_mini_walls,
      arrows_hit: arrows_hit_mini_walls,
      wither_damge: wither_damage_mini_walls,
      wither_kills: wither_kills_mini_walls,
      kit: miniwalls_activeKit,
    },
    party_games: {
      wins: wins_party + wins_party_2 + wins_party_3,
      wins_1: wins_party,
      wins_2: wins_party_2,
      wins_3: wins_party_3,
      round_wins: round_wins_party,
      stars_earned: total_stars_party,
      animal_slaughter_wins: animal_slaughter_round_wins_party,
      animal_slaughter_kills: animal_slaughter_kills_party,
      animal_slaughter_best_score: animal_slaughter_best_score_party,
      anvil_spleef_wins: anvil_spleef_round_wins_party,
      anvil_spleef_best_time: anvil_spleef_best_time_party,
      bombardment_wins: bombardment_round_wins_party,
      bombardment_best_time: bombardment_best_time_party,
      chicken_rings_wins: chicken_rings_round_wins_party,
      chicken_rings_best_time: chicken_rings_best_time_party,
      dive_wins: dive_round_wins_party,
      dive_total_score: dive_total_score_party,
      dive_best_score: dive_best_score_party,
      high_ground_wins: high_ground_round_wins_party,
      high_ground_total_score: high_ground_total_score_party,
      high_ground_best_score: high_ground_best_score_party,
      hoe_hoe_hoe_wins: hoe_hoe_hoe_round_wins_party,
      hoe_hoe_hoe_total_score: hoe_hoe_hoe_total_score_party,
      hoe_hoe_hoe_best_score: hoe_hoe_hoe_best_score_party,
      jigsaw_rush_wins: jigsaw_rush_round_wins_party,
      jigsaw_rush_best_time: jigsaw_rush_best_time_party,
      jungle_jump_wins: jungle_jump_round_wins_party,
      jungle_jump_best_time: jungle_jump_best_time_party,
      lab_escape_wins: lab_escape_round_wins_party,
      lab_escape_best_time: lab_escape_best_time_party,
      lawn_moower_wins: lawn_moower_round_wins_party,
      lawn_moower_mowed_total_score: lawn_moower_mowed_total_score_party,
      lawn_moower_best_score: lawn_moower_mowed_best_score_party,
      minecart_racing_wins: minecart_racing_round_wins_party,
      minecart_racing_best_time: minecart_racing_best_time_party,
      rpg_16_wins: rpg_16_round_wins_party,
      rpg_16_total_score: rpg_16_kills_party,
      rpg_16_best_score: rpg_16_kills_best_score_party,
      spider_maze_wins: spider_maze_round_wins_party,
      spider_maze_best_time: spider_maze_best_time_party,
      the_floor_is_lava_wins: the_floor_is_lava_round_wins_party,
      the_floor_is_lava_best_time: the_floor_is_lava_best_time_party,
      avalanche_wins: avalanche_round_wins_party,
      volcano_wins: volcano_round_wins_party,
      pig_fishing_wins: pig_fishing_round_wins_party,
      pig_jousting_wins: pig_jousting_round_wins_party,
      trampolinio_wins: trampolinio_round_wins_party,
      workshop_wins: workshop_round_wins_party,
      shooting_range_wins: shooting_range_round_wins_party,
      frozen_floor_wins: frozen_floor_round_wins_party,
      cannon_painting_wins: cannon_painting_round_wins_party,
      fire_leapers_wins: fire_leapers_round_wins_party,
      super_sheep_wins: super_sheep_round_wins_party,
    },
    pixel_painters: {
      wins: wins_draw_their_thing,
    },
    throw_out: {
      wins: wins_throw_out,
      kills: kills_throw_out,
      deaths: deaths_throw_out,
    },
    bounty_hunters: {
      wins: wins_oneinthequiver,
      kills: kills_oneinthequiver,
      deaths: deaths_oneinthequiver,
      bounty_kills: bounty_kills_oneinthequiver,
      bow_kills: bow_kills_oneinthequiver,
      sword_kills: sword_kills_oneinthequiver,
    },
    galaxy_wars: {
      wins: sw_game_wins,
      kills: sw_kills,
      deaths: sw_deaths,
      rebel_kills: sw_rebel_kills,
      empire_kills: sw_empire_kills,
      shots_fired: sw_shots_fired,
    },
    farm_hunt: {
      wins: wins_farm_hunt,
      animal_wins: animal_wins_farm_hunt,
      hunter_wins: hunter_wins_farm_hunt,
      kills: kills_farm_hunt,
      animal_kills: animal_kills_farm_hunt,
      hunter_kills: hunter_kills_farm_hunt,
      bow_kills: bow_kills_farm_hunt,
      animal_bow_kills: animal_bow_kills_farm_hunt,
      hunter_bow_kills: hunter_bow_kills_farm_hunt,
      taunts_used: taunts_used_farm_hunt,
      safe_taunts_used: safe_taunts_used_farm_hunt,
      risky_taunts_used: risky_taunts_used_farm_hunt,
      dangerous_taunts_used: dangerous_taunts_used_farm_hunt,
      fireworks_used: firework_taunts_used_farm_hunt,
      poop_collected: poop_collected + poop_collected_farm_hunt,
    },
    football: {
      wins: wins_soccer,
      goals: goals_soccer,
      powerkicks: powerkicks_soccer,
      kicks: kicks_soccer,
    },
    creeper_attack: {
      best_wave: max_wave,
    },
    hole_in_the_wall: {
      wins: wins_hole_in_the_wall,
      rounds: rounds_hole_in_the_wall,
      highest_score_qualification: hitw_record_q,
      highest_score_finals: hitw_record_f,
    },
    hide_and_seek: {
      prop_hunt_hider_wins: prop_hunt_hider_wins_hide_and_seek,
      prop_hunt_seeker_wins: prop_hunt_seeker_wins_hide_and_seek,
      prop_hunt_wins: prop_hunt_hider_wins_hide_and_seek + prop_hunt_seeker_wins_hide_and_seek,
      party_pooper_seeker_wins: party_pooper_seeker_wins_hide_and_seek,
      party_pooper_hider_wins: party_pooper_hider_wins_hide_and_seek,
      party_pooper_wins: party_pooper_seeker_wins_hide_and_seek + party_pooper_hider_wins_hide_and_seek,
      seeker_wins: seeker_wins_hide_and_seek,
      hider_wins: hider_wins_hide_and_seek,
      wins: seeker_wins_hide_and_seek + hider_wins_hide_and_seek,
    },
    zombies: {
      wins: wins_zombies,
      alien_arcadium_wins: wins_zombies_alienarcadium,
      bad_blood_wins: wins_zombies_badblood,
      dead_end_wins: wins_zombies_deadend,
      zombie_kills: zombie_kills_zombies,
      deaths: deaths_zombies,
      total_rounds_survived: total_rounds_survived_zombies,
      bullets_hit: bullets_hit_zombies,
      headshots: headshots_zombies,
      players_revived: players_revived_zombies,
      windows_repaired: windows_repaired_zombies,
      doors_opened: doors_opened_zombies,
      best_round: best_round_zombies,
    },
  };
  // Totals
  let wins = 0;
  let kills = 0;
  Object.values(modes).forEach((mode) => {
    if ('wins' in mode) wins += mode.wins;
    if ('kills' in mode) kills += mode.kills;
  });
  return ({
    coins,
    wins,
    kills,
    modes,
  });
};
