/* eslint-disable camelcase */
/*
* SuperSmash
 */

const {
  getWeeklyStat,
  getMonthlyStat,
  getRatio,
} = require('../../util/utility');

module.exports = ({
  coins = 0,
  kills = 0,
  deaths = 0,
  smashLevel = 0,
  wins = 0,
  losses = 0,
  quits = 0,
  games = 0,
  win_streak = 0,
  kills_weekly_a = 0,
  kills_weekly_b = 0,
  kills_monthly_a = 0,
  kills_monthly_b = 0,
  losses_weekly_a = 0,
  losses_weekly_b = 0,
  losses_monthly_a = 0,
  losses_monthly_b = 0,
  games_weekly_a = 0,
  games_weekly_b = 0,
  games_monthly_a = 0,
  games_monthly_b = 0,
  wins_weekly_a = 0,
  wins_weekly_b = 0,
  wins_monthly_a = 0,
  wins_monthly_b = 0,
  active_class = null,
  class_stats = {},
  'votes_Strawberry Towers': votes_StrawberryTowers = 0,
  votes_Toybox = 0,
  votes_Gunmetal = 0,
  'votes_Color Clash': votes_ColorClash = 0,
  votes_Triplets = 0,
  votes_Luxor = 0,
  votes_Cubed = 0,
}) => ({
  coins,
  kills,
  deaths,
  smash_level: smashLevel,
  kd: getRatio(kills, deaths),
  wins,
  losses,
  quits,
  win_streak,
  wl: getRatio(wins, losses),
  games_played: games,
  weekly_kills: getWeeklyStat(kills_weekly_a, kills_weekly_b),
  weekly_wins: getWeeklyStat(wins_weekly_a, wins_weekly_b),
  weekly_losses: getWeeklyStat(losses_weekly_a, losses_weekly_b),
  weekly_games_played: getWeeklyStat(games_weekly_a, games_weekly_b),
  monthly_kills: getMonthlyStat(kills_monthly_a, kills_monthly_b),
  monthly_wins: getMonthlyStat(wins_monthly_a, wins_monthly_b),
  monthly_losses: getMonthlyStat(losses_monthly_a, losses_monthly_b),
  monthly_games_played: getMonthlyStat(games_monthly_a, games_monthly_b),
  active_class,
  class_stats,

  votes: {
    strawberry_towers: votes_StrawberryTowers,
    toybox: votes_Toybox,
    gunmetal: votes_Gunmetal,
    color_clash: votes_ColorClash,
    triplets: votes_Triplets,
    luxor: votes_Luxor,
    cubed: votes_Cubed,
  },
});
