/* eslint-disable camelcase */
/*
 * Walls
 */

const {
  getWeeklyStat,
  getMonthlyStat,
  getRatio,
} = require('../../util/utility');

module.exports = ({
  assists = 0,
  coins = 0,
  deaths = 0,
  kills = 0,
  losses = 0,
  wins = 0,
  monthly_assists_a = 0,
  monthly_assists_b = 0,
  monthly_kills_a = 0,
  monthly_kills_b = 0,
  monthly_wins_a = 0,
  monthly_wins_b = 0,
  weekly_assists_a = 0,
  weekly_assists_b = 0,
  weekly_kills_a = 0,
  weekly_kills_b = 0,
  weekly_wins_a = 0,
  weekly_wins_b = 0,
  blood,

  // Basic starters
  dwarwen_skills = 0,
  grave_digger = 0,
  hunter = 0,
  stone_guardian = 0,
  master_troll = 0,
  sage = 0,
  chef = 0,
  farmer = 0,
  redstone_expert = 0,
  step = 0,
  trap_engineer = 0,
  escapist = 0,
  blacksmith = 0,
  snack_lover = 0,
  guitarist = 0,
  ready = 0,
  bacon = 0,
  fisherman = 0,
  bomberman = 0,
  chemist = 0,
  smart_boy = 0,
  canadian = 0,
  necromancer = 0,
  lazyman = 0,
  artisan = 0,
  cats_eye = 0,
  fireproof = 0,

  // Advanced starters
  boss_skills = 0,
  boss_digger = 0,
  boss_guardian = 0,
  scotsman = 0,
  insane_farmer = 0,
  thats_hot = 0,
  gold_rush = 0,
  leather_worker = 0,
  soup_drinker = 0,
  really_shiny = 0,
  pyromaniac = 0,
  einstein = 0,
  skybase_king = 0,
  burn_baby_burn = 0,
  very_fortunate = 0,
  get_to_the_choppa = 0,
  creeper_egg = 0,

  // Perks
  adrenaline = 0,
  berserk = 0,
  chainkiller = 0,
  expert_miner = 0,
  final_form = 0,
  fortune = 0,
  haste = 0,
  opportunity = 0,
  shout_count = 0,
  swift = 0,
  tenacity = 0,
  vampirism = 0,
  vitality = 0,

  votes_Egypt = 0,
  votes_LoveLand = 0,
  Inventory,
  InventoryLayout,
  packages,
}) => ({
  assists,
  coins,
  deaths,
  kills,
  losses,
  wins,
  kd: getRatio(kills, deaths),
  win_loss: getRatio(wins, losses),
  win_percentage: getRatio(wins, wins + losses),
  monthly_assists: getMonthlyStat(monthly_assists_a, monthly_assists_b),
  monthly_kills: getMonthlyStat(monthly_kills_a, monthly_kills_b),
  monthly_wins: getMonthlyStat(monthly_wins_a, monthly_wins_b),
  weekly_assists: getWeeklyStat(weekly_assists_a, weekly_assists_b),
  weekly_kills: getWeeklyStat(weekly_kills_a, weekly_kills_b),
  weekly_wins: getWeeklyStat(weekly_wins_a, weekly_wins_b),

  basic_starters: {
    dwarven_skills: dwarwen_skills,
    grave_digger,
    hunter,
    stone_guardian,
    master_troll,
    sage,
    chef,
    farmer,
    redstone_expert,
    watch_your_step: step,
    trap_engineer,
    escapist,
    blacksmith,
    snack_lover,
    guitarist,
    ready_for_anything: ready,
    bacon,
    fisherman,
    bomberman,
    chemist,
    smart_boy,
    canadian,
    necromancer,
    lazy_man: lazyman,
    artisan,
    cats_eye,
    fireproof,
  },
  advanced_starters: {
    boss_skills,
    boss_digger,
    boss_guardian,
    scotsman,
    insane_farmer,
    thats_hot,
    gold_rush,
    leather_worker,
    soup_drinker,
    really_shiny,
    pyromaniac,
    einstein,
    skybase_king,
    burn_baby_burn,
    very_fortunate,
    get_to_the_choppa,
    champion: creeper_egg,
  },
  perks: {
    adrenaline,
    berserk,
    chainkiller,
    expert_miner,
    final_form,
    fortune,
    haste,
    opportunity,
    shout_count,
    swift,
    tenacity,
    vampirism,
    vitality,
  },
  votes: {
    egypt: votes_Egypt,
    loveland: votes_LoveLand,
  },
  settings: {
    blood,
  },
  inventory: Inventory,
  inventory_layout: InventoryLayout,
  packages,
});
