/* eslint-disable camelcase */
/*
 * Walls
 */

const {
  getWeeklyStat,
  getMonthlyStat,
} = require('../../util/utility');

module.exports = ({
  assists,
  coins,
  deaths,
  kills,
  losses,
  wins,
  monthly_assists_a,
  monthly_assists_b,
  monthly_kills_a,
  monthly_kills_b,
  monthly_wins_a,
  monthly_wins_b,
  weekly_assists_a,
  weekly_assists_b,
  weekly_kills_a,
  weekly_kills_b,
  weekly_wins_a,
  weekly_wins_b,
  blood,

  // Basic starters
  dwarwen_skills,
  grave_digger,
  hunter,
  stone_guardian,
  master_troll,
  sage,
  chef,
  farmer,
  redstone_expert,
  step,
  trap_engineer,
  escapist,
  blacksmith,
  snack_lover,
  guitarist,
  ready,
  bacon,
  fisherman,
  bomberman,
  chemist,
  smart_boy,
  canadian,
  necromancer,
  lazyman,
  artisan,
  cats_eye,
  fireproof,

  // Advanced starters
  boss_skills,
  boss_digger,
  boss_guardian,
  scotsman,
  insane_farmer,
  thats_hot,
  gold_rush,
  leather_worker,
  soup_drinker,
  really_shiny,
  pyromaniac,
  einstein,
  skybase_king,
  burn_baby_burn,
  very_fortunate,
  get_to_the_choppa,
  creeper_egg,

  // Perks
  adrenaline,
  berserk,
  chainkiller,
  expert_miner,
  final_form,
  fortune,
  haste,
  opportunity,
  shout_count,
  swift,
  tenacity,
  vampirism,
  vitality,

  votes_Egypt,
  votes_LoveLand,
  Inventory,
  InventoryLayout,
  packages,
}) => ({
  assists,
  coins,
  deaths,
  kills,
  losses,
  wins,
  monthly_assists: getMonthlyStat(monthly_assists_a, monthly_assists_b),
  monthly_kills: getMonthlyStat(monthly_kills_a, monthly_kills_b),
  monthly_wins: getMonthlyStat(monthly_wins_a, monthly_wins_b),
  weekly_assists: getWeeklyStat(weekly_assists_a, weekly_assists_b),
  weekly_kills: getWeeklyStat(weekly_kills_a, weekly_kills_b),
  weekly_wins: getWeeklyStat(weekly_wins_a, weekly_wins_b),

  basic_starters: {
    dwarven_skills: dwarwen_skills,
    grave_digger,
    hunter,
    stone_guardian,
    master_troll,
    sage,
    chef,
    farmer,
    redstone_expert,
    watch_your_step: step,
    trap_engineer,
    escapist,
    blacksmith,
    snack_lover,
    guitarist,
    ready_for_anything: ready,
    bacon,
    fisherman,
    bomberman,
    chemist,
    smart_boy,
    canadian,
    necromancer,
    lazy_man: lazyman,
    artisan,
    cats_eye,
    fireproof,
  },
  advanced_starters: {
    boss_skills,
    boss_digger,
    boss_guardian,
    scotsman,
    insane_farmer,
    thats_hot,
    gold_rush,
    leather_worker,
    soup_drinker,
    really_shiny,
    pyromaniac,
    einstein,
    skybase_king,
    burn_baby_burn,
    very_fortunate,
    get_to_the_choppa,
    champion: creeper_egg,
  },
  perks: {
    adrenaline,
    berserk,
    chainkiller,
    expert_miner,
    final_form,
    fortune,
    haste,
    opportunity,
    shout_count,
    swift,
    tenacity,
    vampirism,
    vitality,
  },
  votes: {
    egypt: votes_Egypt,
    loveland: votes_LoveLand,
  },
  settings: {
    blood,
  },
  inventory: Inventory,
  inventory_layout: InventoryLayout,
  packages,
});
