const got = require('got');
const config = require('../config');

const badItems = [
  'SHADOW_ASSASSIN_BOOTS',
  'SHADOW_ASSASSIN_HELMET',
  'FROZEN_SCYTHE',
  'FEL_SWORD',
  'LIVID_DAGGER',
  'WITHER_BOOTS',
  'WITHER_LEGGINGS',
  'HOLY_DRAGON_BOOTS',
  'SHADOW_ASSASSIN_LEGGINGS',
  'LAST_BREATH',
  'FLOWER_OF_TRUTH',
  'STONE_BLADE',
  'STARRED_BONZO_MASK',
  'NECROMANCER_LORD_BOOTS',
  'WITHER_CHESTPLATE',
  'MENDER_FEDORA',
  'GIANTS_SWORD',
  'TANK_WITHER_CHESTPLATE',
  'STARRED_SHADOW_ASSASSIN_CHESTPLATE',
  'POWER_WITHER_HELMET',
  'WISE_WITHER_HELMET',
  'WISE_WITHER_BOOTS',
  'HOLY_DRAGON_LEGGINGS',
  'WITHER_GOGGLES',
  'SHADOW_GOGGLES',
  'STARRED_SHADOW_ASSASSIN_HELMET',
  'STARRED_BONZO_STAFF',
  'JERRY_STAFF',
  'DIAMOND_NECRON_HEAD',
  'SPEED_WITHER_BOOTS',
  'PERFECT_HELMET_1',
  'TANK_WITHER_BOOTS',
  'SPEED_WITHER_LEGGINGS',
  'ZOMBIE_CHESTPLATE',
  'HOLY_DRAGON_HELMET',
  'HOLY_DRAGON_CHESTPLATE',
  'ZOMBIE_BOOTS',
  'ZOMBIE_LEGGINGS',
  'ASTRAEA',
  'SCYLLA',
  'METAL_CHESTPLATE',
  'YETI_SWORD',
  'PERFECT_CHESTPLATE_3',
  'STARRED_ADAPTIVE_BOOTS',
  'PERFECT_BOOTS_5',
  'AXE_OF_THE_SHREDDED',
  'SPEED_WITHER_CHESTPLATE',
  'DIAMOND_THORN_HEAD',
  'DIAMOND_PROFESSOR_HEAD',
  'STARRED_ADAPTIVE_CHESTPLATE',
  'TERMINATOR',
];

(async function run() {
  await Promise.all(badItems.map(async (id) => {
    console.log(`DELETE ${config.ITEMS_HOST}/${id}`);
    return got.delete(`${config.ITEMS_HOST}/${id}`).json();
  }));
}());
